name: mattermost_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "3.7.2"
  flutter: "3.29.3"

dependencies:
  flutter:
    sdk: flutter

  mattermost_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
